COVALENT = "covalent" # bool; former FEATURENAME_COVALENT
ELECTROSTATIC = "electrostatic" # float; former FEATURENAME_EDGECOULOMB
VANDERWAALS = "vanderwaals" # float; former FEATURENAME_EDGEVANDERWAALS
DISTANCE = "distance" # float; former FEATURENAME_EDGEDISTANCE
SAMECHAIN = "same_chain" # bool; former FEATURE_EDGE_INTERACTIONTYPE & FEATURENAME_EDGESAMECHAIN
