
# node features
FEATURENAME_POSITION = "pos"
FEATURENAME_AMINOACID = "type"
FEATURENAME_CHAIN = "chain"
FEATURENAME_CHARGE = "charge"
FEATURENAME_POLARITY = "polarity"
FEATURENAME_BURIEDSURFACEAREA = "bsa"
FEATURENAME_HALFSPHEREEXPOSURE = "hse"
FEATURENAME_PSSM = "pssm"
FEATURENAME_CONSERVATION = "conservation"
FEATURENAME_INFORMATIONCONTENT = "ic"
FEATURENAME_RESIDUEDEPTH = "depth"
FEATURENAME_PSSMDIFFERENCE = "pssm_difference"
FEATURENAME_SASA = "sasa"

# edge features
FEATURENAME_EDGECOULOMB = "coulomb"
FEATURENAME_EDGEVANDERWAALS = "vanderwaals"
FEATURENAME_EDGEDISTANCE = "dist"
FEATURENAME_EDGETYPE = "type"
