# GRAPH GROUPS
HDF5KEY_GRAPH_NODEFEATURES = "node_features"
HDF5KEY_GRAPH_EDGEFEATURES = "edge_features"
HDF5KEY_GRAPH_TARGETVALUES = "target_values"

# GRAPH IDENTIFYERS
HDF5KEY_GRAPH_NAMES = "_names"
HDF5KEY_GRAPH_INDICES = "_indices"

# GRIDS
HDF5KEY_GRID_GRIDPOINTS = "grid_points"
HDF5KEY_GRID_X = "x"
HDF5KEY_GRID_Y = "y"
HDF5KEY_GRID_Z = "z"
HDF5KEY_GRID_CENTER = "center"
HDF5KEY_GRID_MAPPEDFEATURES = "mapped_features"
HDF5KEY_GRID_MAPPEDFEATURESVALUE = "mapped_features_value"

